# Generated by Django 6.0.6 on 2026-07-05 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='ADDRESS',
        ),
        migrations.AlterModelTable(
            name='user',
            table='USER',
        ),
    ]
